### ISSUE TITLE
No license in repo

### ISSUE THREAD

**Issue by amitra93** [psambit9791/wavfile#3]
This is preventing my usage of this repo for a work project.

Please accept https://github.com/psambit9791/wavfile/pull/2.

**Comment by amitra93** [comment]
@psambit9791

**Comment by psambit9791** [comment]
Hi @amitra93 , I can only get to this in the weekend.

**Comment by amitra93** [comment]
Thanks for the response! Yeah that's fine.

**Comment by amitra93** [comment]
Hi, would you be able to get to this sometime this week?

**Comment by psambit9791** [comment]
Added. This is now available in Maven as well - versioned as 1.0.0.
